### ISSUE TITLE
sentence-transformers does not pick torch_dtype from model config

### ISSUE THREAD

**Issue by satyamk7054** [UKPLab/sentence-transformers#2579] opened 2024-04-06 07:32 UTC
Hi,

SentenceTransformers does not use the torch_dtype specified in the model config. New models like [e5-mistral-7b-instruct](https://huggingface.co/intfloat/e5-mistral-7b-instruct) are larger in size and use FP16 as the dtype. However, when loaded using SentenceTransformers, the model is loaded with FP32 dtype. 

This is because HF transformers uses FP32 as the default unless torch_dtype='auto' is passed, as mentioned [here](https://huggingface.co/docs/transformers/en/main_classes/model#transformers.PreTrainedModel.from_pretrained.torch_dtype).

I've tried to fix the issue in https://github.com/UKPLab/sentence-transformers/pull/2578.

Thank you

**Comment by tomaarsen** [comment] 2024-04-08 07:53
Hello!

I'm afraid that I cannot accept your proposal in #2578. I understand that some models are recommended to be used in fp16 or bf16, but setting the torch_dtype to "auto" for everyone would result in breaking changes: people's embedding models would give different results when updating to the next version.

I think the proper solution is to more clearly expose the `torch_dtype` parameter such that users can use whatever dtype they choose when loading a model. #2426 introduces a proposal that tries to address this.

- Tom Aarsen

**Comment by satyamk7054** [comment] 2024-04-08 17:22
> Hello!
> 
> I'm afraid that I cannot accept your proposal in #2578. I understand that some models are recommended to be used in fp16 or bf16, but setting the torch_dtype to "auto" for everyone would result in breaking changes: people's embedding models would give different results when updating to the next version.
> 
> I think the proper solution is to more clearly expose the `torch_dtype` parameter such that users can use whatever dtype they choose when loading a model. #2426 introduces a proposal that tries to address this.
> 
> * Tom Aarsen

@tomaarsen Thank you for your response!

That's a very valid point on compatibility. I think https://github.com/UKPLab/sentence-transformers/pull/2426 does not handle this particular issue. This is because HF transformers does not pick dtype from config unless you pass "auto" as the dtype when loading the model, as mentioned [here](https://huggingface.co/docs/transformers/en/main_classes/model#transformers.PreTrainedModel.from_pretrained.torch_dtype).

Exposing kwargs in SentenceTransformers makes sense. However, if you pass dtype="auto" to that, at the moment it fails in Transformers because we pass those kwargs to both AutoConfig and AutoModel:
- AutoConfig does not accept "auto" and seems to fail with `AttributeError: 'str' object has no attribute 'is_floating_point'`
HuggingFace implementation even has an [explicit check for handling this](https://github.com/huggingface/transformers/blob/8c00b53eb01051e93942e99912455883b7ea47b2/src/transformers/models/auto/auto_factory.py#L517)

One way to fix this would be to pass only the kwargs to from_pretrained instead of both the self-built config object as well as the kwargs (the AutoModel class will build the config object). Given we need to have checks like `isinstance(config, T5Config)`, we'd need to build the config once using `AutoConfig.from_pretrained(model_name_or_path, cache_dir=cache_dir)` (note: no model_args passed), but we do not pass it to AutoModel.from_pretrained

If this makes sense, I can make the required changes.

**Comment by tomaarsen** [comment] 2024-04-09 09:31
> Exposing kwargs in SentenceTransformers makes sense. However, if you pass dtype="auto" to that, at the moment it fails in Transformers because we pass those kwargs to both AutoConfig and AutoModel:

Indeed, we have to be a bit smarter here I think. Perhaps the nicest solution is to avoid explicitly creating the config altogether, but just using `AutoModel` instead. I'm not sure if we reduce the configuration options for ST then, though.

**Comment by satyamk7054** [comment] 2024-04-16 19:44
> > Exposing kwargs in SentenceTransformers makes sense. However, if you pass dtype="auto" to that, at the moment it fails in Transformers because we pass those kwargs to both AutoConfig and AutoModel:
> 
> Indeed, we have to be a bit smarter here I think. Perhaps the nicest solution is to avoid explicitly creating the config altogether, but just using `AutoModel` instead. I'm not sure if we reduce the configuration options for ST then, though.

Makes sense. How about I do what I suggested for this issue / PR (not pass args to AutoConfig) and as a follow-up we can improve the logic to just rely on AutoModel?

**Comment by satyamk7054** [comment] 2024-04-24 08:22
@tomaarsen I understand you want to use https://github.com/UKPLab/sentence-transformers/pull/2426 as one way to solve this. Could you please let me know when that PR will be merged?

If it'll take a long time, could we please enable dtype in the interim using my PR (open to any suggestions)? There's a significant difference in inference time using float32 v/s float16 (166.58ms v/s 35.8ms for a ~64 token string)

**Comment by tomaarsen** [comment] 2024-04-24 10:15
In the last few days I had another look at #2426 to see whether I can include it in the next version, but I think that my consensus for now is that it is too hacky. 
Instead, I think the best solution is to move forward with your PR: #2578. I do have some suggestions on API differences that I think might be best. I'll write out those comments in the PR.

I'll also request reviews from people who work on `transformers` as the API changes are fairly drastic.

- Tom Aarsen

**Comment by fengshansi** [comment] 2024-05-19 07:59
When will the next version be released?

**Comment by tomaarsen** [comment] 2024-05-21 07:38
The next release, v3.0, will likely be this month. #2578 will be included.

- Tom Aarsen

**Closed** 2024-05-22 12:27 UTC

**Comment by rangehow** [comment] 2025-01-06 07:06
```python
model = SentenceTransformer(model_name, trust_remote_code=True, device=device, model_kwargs={"torch_dtype": "auto",}, tokenizer_kwargs={"model_max_length": 8192, "truncation": True})
```
When loading `jina-embeddings-v3`  
```bash
'str' object has no attribute 'is_floating_point'
```

**Comment by devashishraj** [comment] 2025-02-23 17:16
> model = SentenceTransformer(model_name, trust_remote_code=True, device=device, model_kwargs={"torch_dtype": "auto",}, tokenizer_kwargs={"model_max_length": 8192, "truncation": True})
> When loading `jina-embeddings-v3`
> 
> 'str' object has no attribute 'is_floating_point'

Found any solution ? @rangehow

**Comment by tomaarsen** [comment] 2025-02-24 09:15
Is this specific to the `jina-embeddings-v3` model? They have some custom code on their side that may be the cause instead.
