### ISSUE TITLE
Error while downloading all-MiniLM-L6-v2 from huggingface - data_config.json file

### ISSUE THREAD

**Issue by dingusagar** [UKPLab/sentence-transformers#2420] opened 2024-01-17 12:48 UTC
Using sentence-transformers==2.2.2
I am having a gunicorn with fastapi setup with 4 workers. 

During the app startup, getting these errors while trying to load the sbert model. 

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/.cache/torch/sentence_transformers/sentence-transformers_all-MiniLM-L6-v2/data_config.json.lock'

at .snapshot_download ( /usr/local/lib/python3.10/site-packages/sentence_transformers/util.py:494 )
at .__init__ ( /usr/local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py:87 )
at .<module> ( /app/aqm/utils/similarity_utils.py:6 )
at .<module> ( /app/aqm/services/condition_extraction/conditions_extractor_v2.py:3 )
at .<module> ( /app/aqm/services/stability_extraction/stability_relation_extractor_v4.py:5 )
at .<module> ( /app/aqm/routers/qa_router.py:10 )
at .<module> ( /app/main.py:4 )
at ._call_with_frames_removed ( <frozen importlib._bootstrap>:241 )
at .exec_module ( <frozen importlib._bootstrap_external>:883 )
at ._load_unlocked ( <frozen importlib._bootstrap>:688 )
at ._find_and_load_unlocked ( <frozen importlib._bootstrap>:1006 )
at ._find_and_load ( <frozen importlib._bootstrap>:1027 )
at ._gcd_import ( <frozen importlib._bootstrap>:1050 )
at .import_module ( /usr/local/lib/python3.10/importlib/__init__.py:126 )
at .import_app ( /usr/local/lib/python3.10/site-packages/gunicorn/util.py:371 )
at .load_wsgiapp ( /usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py:48 )
at .load ( /usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py:58 )
at .wsgi ( /usr/local/lib/python3.10/site-packages/gunicorn/app/base.py:67 )
at .load_wsgi ( /usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py:146 )
at .init_process ( /usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py:134 )
at .init_process ( /usr/local/lib/python3.10/site-packages/uvicorn/workers.py:66 )
at .spawn_worker ( /usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py:609 )
```

**Comment by tomaarsen** [comment] 2024-01-17 13:36
Hello!

I'm trying to reproduce this exactly, but am failing to. However, I theorize that this is failing because each of the 4 workers are initializing the model roughly simultaneously, and some of them are sometimes keeping a `.lock` on the `data_config.json`? One of the somewhat odd things is that the `data_config.json` is not actually used by the model at all, it's a file much like a `README.md` - just there for information.

I do have a suggestion for you: consider `preload`-ing your app before spawning the workers. Then you only load the model once, rather than 4 times. See e.g. this [medium](https://medium.com/trendyol-tech/sharing-large-language-models-among-gunicorn-workers-reducing-memory-usage-and-boosting-18c0efd8e942) for more information.

e.g.
```
gunicorn app:main --workers=4 --preload
```

Does that help your problem somewhat?

- Tom Aarsen

**Comment by dingusagar** [comment] 2024-01-17 17:47
Thanks for the reply @tomaarsen ,

Yes, I did notice that data_config.json is not really useful for inference. 
I am also not able to reproduce this locally, it happens when I deploy it to a GCP cloud-run service. 

preload is a good suggestion, I will try it. 
But one question I have is, if I preload the model object will be shared among the workers and wouldn't it reduce the parallelism capability of the system? 

My goal of adding 4 workers was to scale up the system's throughput. But if model object is shared, then only one worker can access it at an instant, right?

**Comment by tomaarsen** [comment] 2024-01-17 17:58
That's a good question. I must admit that I'm not quite sure - it would make sense that it's indeed a bit slower... If so, we could avoid the preload. Perhaps it can be resolved by downloading the model repository `git clone https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2 sbert_model` followed by `rm sbert_model/data_config.json`. Then, in Python, `SentenceTransformer("all-MiniLM-L6-v2")` becomes `SentenceTransformer("sbert_model")`.

I'm not 100% sure that it'll work, but it seems like a reasonable plan.

- Tom Aarsen

**Comment by dingusagar** [comment] 2024-01-17 18:12
yeah, I guess this is another option to try. Thanks, will try it out.

**Closed** 2024-01-29 10:14 UTC
