### ISSUE TITLE
Different batch sizes lead to different embeddings in SentenceTransformer.encode()

### ISSUE THREAD

**Issue by gustavz** [UKPLab/sentence-transformers#2312] opened 2023-09-22 09:50 UTC
My expectation is that batch size has no impact on embedding results, but this is not the case.
Different batch sizes lead to different embeddings. 

The difference is not huge, but big enough if used in a vector database for document retrieval to get different results and therefore  drastically change any downstream application results.

This is not expected for ML inference.

Is this only due to floating point precision? 
And is there any known way to solve this issue and get consistent results?

Example:
```python
import random
from sentence_transformers import SentenceTransformer

random.seed(42)

model_name = "sentence-transformers/all-mpnet-base-v2"

words = ['Any', 'shuffled', 'words', 'form', 'a', 'sentence', '.']
texts = [' '.join([random.choice(words) for _ in range(10)]) for _ in range(100)]

st = SentenceTransformer(model_name)

e0 = st.encode(texts, batch_size=32).tolist()
e1 = st.encode(texts, batch_size=1).tolist()
e2 = st.encode(texts, batch_size=32).tolist()

print(e0 == e1, e1 == e2, e0 == e2)

>>> False False True
```

**Comment by carlesoctav** [comment] 2023-09-23 05:07
Perhaps you should consider using NumPy's assert instead of a list. I couldn't replicate any issues with this script."
```python
import random
from sentence_transformers import SentenceTransformer
import numpy as np

random.seed(42)

model_name = "sentence-transformers/all-mpnet-base-v2"

words = ["Any", "shuffled", "words", "form", "a", "sentence", "."]
texts = [" ".join([random.choice(words) for _ in range(10)]) for _ in range(10)]

st = SentenceTransformer(model_name)

e0 = st.encode(texts, batch_size=32)
print(f"==>> type(e0): {type(e0)}")
print(f"==>> e0: {e0}")
e1 = st.encode(texts, batch_size=1)
print(f"==>> e1: {e1}")
e2 = st.encode(texts, batch_size=32)
print(f"==>> e2: {e2}")

np.testing.assert_allclose(e0, e1, atol=1e-5)
np.testing.assert_allclose(e0, e2, atol=1e-5)
np.testing.assert_allclose(e1, e2, atol=1e-5)
```

**Comment by andersfylling** [comment] 2023-09-23 21:01
`atol` means you're saying that a minor difference in the values is okay. Isn't that the problem in the first place? `0.00001 ` is quite large...

**Comment by carlesoctav** [comment] 2023-09-24 01:59
> `atol` implies that you are accepting minor differences in the values, but isn't that the issue we're trying to address in the first place? A 0.00001 error margin seems relatively large...

Yes, `atol` represents the tolerance for differences between two ndarrays. It's worth noting that when using a smaller tolerance like 1e-9, the test still passes.

**Comment by andersfylling** [comment] 2023-09-24 03:35
@gustavz could you share the output of `python -c "import pydantic.version; print(pydantic.version.version_info())"`

**Comment by gustavz** [comment] 2023-09-25 07:26
@carlesoctav You can directly compare the numpy arrays, it's the same issue, I just used lists as the comparison is simpler:
```python
import numpy as np
from sentence_transformers import SentenceTransformer

model_name = "sentence-transformers/all-mpnet-base-v2"

texts = ["some simple text" for _ in range(10)]

st = SentenceTransformer(model_name)

e0 = st.encode(texts, batch_size=32)
e1 = st.encode(texts, batch_size=1)
e2 = st.encode(texts, batch_size=32)

np.testing.assert_array_equal(e0, e1)

>>> AssertionError
```
The difference exists even for the most simplest all identical strings and is ofc bigger for real world examples.
And as I said using SentenceTransformer to create embeddings for LLM RAG applications leads to changing batch sizes changing the resulting retrieved documents drastically.


@andersfylling 
```
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.2.1
        pydantic-core version: 2.6.1
          pydantic-core build: profile=release pgo=false
                 install path: .../env/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 21 2023, 16:38:31) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.5.2-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by gustavz** [comment] 2023-09-25 07:30
And yeah sure, you can get `np.testing.assert_allclose(e1, e2)` to be `True` if you reduce `atol` below the default.
But again, this is a toy example, with identical strings, the resulting difference is not expected to be that high.

**Comment by gustavz** [comment] 2023-09-25 08:05
> Yes, atol represents the tolerance for differences between two ndarrays. It's worth noting that when using a smaller tolerance like 1e-9, the test still passes.
This is not True, or at least not on any machine that I tested

**Comment by ir2718** [comment] 2023-09-28 22:00
@gustavz It turns out that this is an issue with the underlying Huggingface transformers library. I experienced the same issue using the AutoModel class directly.

https://github.com/huggingface/transformers/issues/2401

**Comment by jianjennygong** [comment] 2023-10-01 17:04
I'm experiencing the same issue. Any update?

**Comment by tomaarsen** [comment] 2023-11-07 20:07
I can reproduce this behaviour, and I can indeed narrow it down to the underlying `transformers` model. In my findings, I get a discrepancy of about 1e-7. Luckily, this shouldn't notably affect semantic search, similarity, etc. behaviour. I will await further updates from `transformers` rather than trying to fix it in `sentence-transformers`.

- Tom Aarsen

**Comment by Hannibal046** [comment] 2023-12-21 10:15
maybe it is about the padding?

**Comment by tomaarsen** [comment] 2024-01-18 15:38
I'll close this, as the difference does not seem to originate from `sentence-transformers`. In truth, I expect that perhaps it originates in `torch` or even lower-level, and that it's just due to arbitrary rounding, as the differences are very tiny.

- Tom Aarsen

**Closed by tomaarsen** 2024-01-18 15:38 UTC
